Repository googleapis/gapic-generator-php, pull requests merged in 2021-12, with the labels that each got.

#419 chore: switch from master to main
  .github/release-please.yml
  .github/workflows/bazel_example.yml
  .github/workflows/phpunit.yml
  DEVELOPMENT.md
Labels: cla: yes

#421 chore: remove main branch
  .github/workflows/bazel_example.yml
  .github/workflows/phpunit.yml
Labels: automerge, cla: yes

#422 chore: use actools-php instead of actools as owner
  .github/CODEOWNERS
Labels: automerge, cla: yes

#424 fix(diregapic): use camelCase field name in custom op test
  src/Generation/UnitTestsGenerator.php
Labels: automerge
