Repository googleapis/gapic-generator-php, pull requests merged in 2021-07, with the labels that each got.

#317 fix(build): Forego errors when clearing Bazel cache [ggp]
  .github/workflows/bazel_example.yml
Labels: cla: yes

#320 chore: Add baseline goldens for required oneofs [ggp]
  .githooks/pre-commit
  .github/workflows/phpunit.yml
  composer.json
  tests/Unit/ProtoTests/BasicOneof/basic-oneof.proto
  tests/Unit/ProtoTests/BasicOneof/basic-oneof_gapic.yaml
  tests/Unit/ProtoTests/BasicOneof/out/src/BasicOneofClient.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Gapic/BasicOneofGapicClient.php
  tests/Unit/ProtoTests/BasicOneof/out/src/gapic_metadata.json
  tests/Unit/ProtoTests/BasicOneof/out/src/resources/basic_oneof_client_config.json
  tests/Unit/ProtoTests/BasicOneof/out/src/resources/basic_oneof_descriptor_config.php
  tests/Unit/ProtoTests/BasicOneof/out/src/resources/basic_oneof_rest_client_config.php
  tests/Unit/ProtoTests/BasicOneof/out/tests/Unit/BasicOneofClientTest.php
  tests/Unit/ProtoTests/GoldenUpdateMain.php
Labels: cla: yes

#322 chore(engx): remove unused param handling code [ggp]
  src/Generation/GapicClientGenerator.php
Labels: cla: yes

#325 feat(oneofs): initial scaffolding and wrapper class for required oneofs [ggp]
  src/CodeGenerator.php
  src/Generation/FieldDetails.php
  src/Generation/MethodDetails.php
  src/Generation/OneofWrapperGenerator.php
  src/Generation/ServiceDetails.php
  src/Generation/TestNameValueProducer.php
  src/Utils/Helpers.php
  tests/Unit/ProtoTests/BasicOneof/basic-oneof.proto
  tests/Unit/ProtoTests/BasicOneof/out/src/Gapic/BasicOneofGapicClient.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Request/SupplementaryDataOneof.php
  tests/Unit/ProtoTests/ProtoTest.php
Labels: cla: yes

#326 feat(oneofs): add private fields to the wrapper oneof class [ggp]
  src/Generation/OneofWrapperGenerator.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Request/SupplementaryDataOneof.php
Labels: cla: yes

#332 chore(engx): Apply linter fixes in IntJsonValidator.php [ggp]
  validation/IntJsonValidator.php
Labels: cla: yes

#316 fix: put useJwtAccessWithScope in credentialsConfig
  src/Generation/GapicClientGenerator.php
  tests/Integration/goldens/compute_small/src/V1/Gapic/AddressesGapicClient.php
  tests/Integration/goldens/compute_small/src/V1/Gapic/RegionOperationsGapicClient.php
  tests/Unit/ProtoTests/BasicDiregapic/out/src/Gapic/LibraryServiceGapicClient.php
Labels: automerge, cla: yes

#321 feat: add mtls clientCertSource client option to docs
  src/Generation/GapicClientGenerator.php
  src/Utils/Type.php
  tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/asset_rest/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/compute_small/src/V1/Gapic/AddressesGapicClient.php
  tests/Integration/goldens/compute_small/src/V1/Gapic/RegionOperationsGapicClient.php
  tests/Integration/goldens/container/src/V1/Gapic/ClusterManagerGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/AutoscalingPolicyServiceGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/JobControllerGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/WorkflowTemplateServiceGapicClient.php
  tests/Integration/goldens/functions/src/V1/Gapic/CloudFunctionsServiceGapicClient.php
  tests/Integration/goldens/iam/src/V1/Gapic/IAMPolicyGapicClient.php
  tests/Integration/goldens/kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  tests/Integration/goldens/logging/src/V2/Gapic/ConfigServiceV2GapicClient.php
  tests/Integration/goldens/logging/src/V2/Gapic/LoggingServiceV2GapicClient.php
  tests/Integration/goldens/logging/src/V2/Gapic/MetricsServiceV2GapicClient.php
  tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
  tests/Integration/goldens/retail/src/V2alpha/Gapic/CatalogServiceGapicClient.php
  tests/Integration/goldens/retail/src/V2alpha/Gapic/PredictionServiceGapicClient.php
  tests/Integration/goldens/retail/src/V2alpha/Gapic/ProductServiceGapicClient.php
  tests/Integration/goldens/retail/src/V2alpha/Gapic/UserEventServiceGapicClient.php
  tests/Integration/goldens/securitycenter/src/V1/Gapic/SecurityCenterGapicClient.php
  tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php
  tests/Integration/goldens/talent/src/V4beta1/Gapic/ApplicationServiceGapicClient.php
  tests/Integration/goldens/talent/src/V4beta1/Gapic/CompanyServiceGapicClient.php
  tests/Integration/goldens/talent/src/V4beta1/Gapic/CompletionGapicClient.php
  tests/Integration/goldens/talent/src/V4beta1/Gapic/EventServiceGapicClient.php
  tests/Integration/goldens/talent/src/V4beta1/Gapic/JobServiceGapicClient.php
  tests/Integration/goldens/talent/src/V4beta1/Gapic/ProfileServiceGapicClient.php
  tests/Integration/goldens/talent/src/V4beta1/Gapic/TenantServiceGapicClient.php
  tests/Integration/goldens/videointelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  tests/Unit/ProtoTests/Basic/out/src/Gapic/BasicGapicClient.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/src/Gapic/BasicBidiStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicClientStreaming/out/src/Gapic/BasicClientStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicDiregapic/out/src/Gapic/LibraryServiceGapicClient.php
  tests/Unit/ProtoTests/BasicLro/out/src/Gapic/BasicLroGapicClient.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Gapic/BasicOneofGapicClient.php
  tests/Unit/ProtoTests/BasicPaginated/out/src/Gapic/BasicPaginatedGapicClient.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/src/Gapic/BasicServerStreamingGapicClient.php
  tests/Unit/ProtoTests/DeprecatedService/out/src/Gapic/DeprecatedServiceGapicClient.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php
  tests/Unit/ProtoTests/ResourceNames/out/src/Gapic/ResourceNamesGapicClient.php
  tests/Unit/ProtoTests/RoutingHeaders/out/src/Gapic/RoutingHeadersGapicClient.php
Labels: automerge, cla: yes

#327 feat(oneofs): Add all methods for oneof wrapper class [ggp]
  src/Generation/OneofWrapperGenerator.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Request/SupplementaryDataOneof.php
Labels: cla: yes

#328 feat(oneofs): add oneof wrapper usage in the Gapic client [ggp]
  src/Ast/AST.php
  src/Generation/FieldDetails.php
  src/Generation/GapicClientGenerator.php
  src/Generation/OneofWrapperGenerator.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Gapic/BasicOneofGapicClient.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Request/SupplementaryDataOneof.php
Labels: cla: yes

#329 fix(oneofs): fix oneof wrapper field access [ggp]
  src/Generation/OneofWrapperGenerator.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Request/SupplementaryDataOneof.php
Labels: cla: yes

#330 feat(oneofs): add oneof wrapper usage in tests [ggp]
  .githooks/pre-commit
  .github/workflows/phpunit.yml
  src/Generation/FieldDetails.php
  src/Generation/GapicClientGenerator.php
  src/Generation/MethodDetails.php
  src/Generation/OneofWrapperGenerator.php
  src/Generation/TestNameValueProducer.php
  src/Generation/UnitTestsGenerator.php
  tests/Unit/ProtoTests/BasicOneof/out/tests/Unit/BasicOneofClientTest.php
Labels: cla: yes

#333 feat(oneofs): add oneofs usage to sample code and polish generated PhpDocs [ggp]
  src/Ast/AST.php
  src/Ast/PhpDoc.php
  src/Generation/FieldDetails.php
  src/Generation/GapicClientExamplesGenerator.php
  src/Generation/GapicClientGenerator.php
  src/Generation/OneofWrapperGenerator.php
  src/Generation/TestNameValueProducer.php
  src/Generation/UnitTestsGenerator.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Gapic/BasicOneofGapicClient.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Request/SupplementaryDataOneof.php
Labels: cla: yes, samples

#336 feat(oneofs): Add support for required oneofs in PHP
  .githooks/pre-commit
  .github/workflows/phpunit.yml
  src/Ast/AST.php
  src/Ast/PhpDoc.php
  src/CodeGenerator.php
  src/Generation/FieldDetails.php
  src/Generation/GapicClientExamplesGenerator.php
  src/Generation/GapicClientGenerator.php
  src/Generation/MethodDetails.php
  src/Generation/OneofWrapperGenerator.php
  src/Generation/ServiceDetails.php
  src/Generation/TestNameValueProducer.php
  src/Generation/UnitTestsGenerator.php
  src/Utils/Helpers.php
  tests/Integration/goldens/dataproc/tests/Unit/V1/AutoscalingPolicyServiceClientTest.php
  tests/Integration/goldens/retail/tests/Unit/V2alpha/UserEventServiceClientTest.php
  tests/Unit/ProtoTests/BasicOneof/basic-oneof.proto
  tests/Unit/ProtoTests/BasicOneof/out/src/Gapic/BasicOneofGapicClient.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Request/SupplementaryDataOneof.php
  tests/Unit/ProtoTests/BasicOneof/out/tests/Unit/BasicOneofClientTest.php
  tests/Unit/ProtoTests/ProtoTest.php
Labels: cla: yes

#349 chore(engx): Update year in unit tests [ggp]
  tests/Tools/GeneratorUtils.php
  tests/Unit/ProtoTests/Basic/out/src/BasicClient.php
  tests/Unit/ProtoTests/Basic/out/src/Gapic/BasicGapicClient.php
  tests/Unit/ProtoTests/Basic/out/tests/Unit/BasicClientTest.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/src/BasicBidiStreamingClient.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/src/Gapic/BasicBidiStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/tests/Unit/BasicBidiStreamingClientTest.php
  tests/Unit/ProtoTests/BasicClientStreaming/out/src/BasicClientStreamingClient.php
  tests/Unit/ProtoTests/BasicClientStreaming/out/src/Gapic/BasicClientStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicClientStreaming/out/tests/Unit/BasicClientStreamingClientTest.php
  tests/Unit/ProtoTests/BasicDiregapic/out/src/Gapic/LibraryServiceGapicClient.php
  tests/Unit/ProtoTests/BasicDiregapic/out/src/LibraryServiceClient.php
  tests/Unit/ProtoTests/BasicDiregapic/out/tests/Unit/LibraryServiceClientTest.php
  tests/Unit/ProtoTests/BasicLro/out/src/BasicLroClient.php
  tests/Unit/ProtoTests/BasicLro/out/src/Gapic/BasicLroGapicClient.php
  tests/Unit/ProtoTests/BasicLro/out/tests/Unit/BasicLroClientTest.php
  tests/Unit/ProtoTests/BasicOneof/out/src/BasicOneofClient.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Gapic/BasicOneofGapicClient.php
  tests/Unit/ProtoTests/BasicOneof/out/src/Request/SupplementaryDataOneof.php
  tests/Unit/ProtoTests/BasicOneof/out/tests/Unit/BasicOneofClientTest.php
  tests/Unit/ProtoTests/BasicPaginated/out/src/BasicPaginatedClient.php
  tests/Unit/ProtoTests/BasicPaginated/out/src/Gapic/BasicPaginatedGapicClient.php
  tests/Unit/ProtoTests/BasicPaginated/out/tests/Unit/BasicPaginatedClientTest.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/src/BasicServerStreamingClient.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/src/Gapic/BasicServerStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/tests/Unit/BasicServerStreamingClientTest.php
  tests/Unit/ProtoTests/DeprecatedService/out/src/DeprecatedServiceClient.php
  tests/Unit/ProtoTests/DeprecatedService/out/src/Gapic/DeprecatedServiceGapicClient.php
  tests/Unit/ProtoTests/DeprecatedService/out/tests/Unit/DeprecatedServiceClientTest.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/GrpcServiceConfigWithRetry1Client.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/tests/Unit/GrpcServiceConfigWithRetry1ClientTest.php
  tests/Unit/ProtoTests/ResourceNames/out/src/Gapic/ResourceNamesGapicClient.php
  tests/Unit/ProtoTests/ResourceNames/out/src/ResourceNamesClient.php
  tests/Unit/ProtoTests/ResourceNames/out/tests/Unit/ResourceNamesClientTest.php
  tests/Unit/ProtoTests/RoutingHeaders/out/src/Gapic/RoutingHeadersGapicClient.php
  tests/Unit/ProtoTests/RoutingHeaders/out/src/RoutingHeadersClient.php
  tests/Unit/ProtoTests/RoutingHeaders/out/tests/Unit/RoutingHeadersClientTest.php
Labels: cla: yes

#350 docs: add back 1.0.3 header in changelog [ggp]
  CHANGELOG.md
Labels: cla: yes
