Repository googleapis/gapic-generator-php, pull requests merged in 2021-03, with the labels that each got.

#136 Use minimized PHP configuration when building from source
  rules_php_gapic/php_repo.bzl
Labels: cla: yes

#137 Update bazel example to show use of beta03
  bazel_example/WORKSPACE.bazel
Labels: cla: yes

#139 Fix (benign) bug in example and text-value config
  src/Generation/GapicClientExamplesGenerator.php
  src/Generation/TestNameValueProducer.php
Labels: cla: yes

#140 chore(engx): Add Vim files to .gitignore [ggphp]
  .gitignore
Labels: cla: yes

#143 chore(build): Add pre-commit hooks [ggphp]
  .githooks/pre-commit
Labels: api: cloudbuild, cla: yes

#142 docs: Add DEVELOPMENT.md [ggphp]
  DEVELOPMENT.md
Labels: cla: yes

#141 fix(grpc_config): Round retry_delay_multiplier for determinstic tests [ggphp]
  .githooks/pre-commit
  src/Generation/ResourcesGenerator.php
Labels: cla: yes

#149 docs: Add DEVELOPMENT.md [ggphp]
  DEVELOPMENT.md
Labels: cla: yes

#150 docs(dev): Add global composer and php-cs-fixer setup [ggphp]
  DEVELOPMENT.md
Labels: cla: yes

#151 Rename 'src' to 'srcs' in bazel php_gapic_library rule
  bazel_example/BUILD.bazel
  rules_php_gapic/php_gapic.bzl
Labels: cla: yes

#152 Fix generated file layout; fix resource-names
  integration_tests/Invoker.php
  integration_tests/Main.php
  src/CodeGenerator.php
  src/Generation/ResourcesGenerator.php
  src/Generation/ServiceDetails.php
  src/Main.php
  src/Utils/Helpers.php
Labels: cla: yes

#144 fix(bazel): Fix Bazel build to work within this repo [ggphp]
  WORKSPACE.bazel
  repositories.bzl
Labels: cla: yes

#153 feat(integration_tests): Add Bazel integration test and golden update rules, add Asset test
  .githooks/pre-commit
  DEVELOPMENT.md
  integration_tests/BUILD.bazel
  integration_tests/goldens/asset/BUILD.bazel
  integration_tests/goldens/asset/src/V1/AssetServiceClient.php
  integration_tests/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  integration_tests/goldens/asset/src/V1/resources/asset_service_client_config.json
  integration_tests/goldens/asset/src/V1/resources/asset_service_descriptor_config.php
  integration_tests/goldens/asset/src/V1/resources/asset_service_rest_client_config.php
  integration_tests/goldens/asset/tests/Unit/V1/AssetServiceClientTest.php
  rules_php_test/integration_test.bzl
Labels: cla: yes

#146 fix(bazel)!: remove unused package option from php_gapic_library [ggphp]
  integration_tests/BUILD.bazel
  rules_php_gapic/php_gapic.bzl
Labels: cla: yes

#147 chore(engx): Apply phpcsfixer lint fixes to src/ [ggphp]
  src/Ast/AST.php
  src/Ast/Expression.php
  src/Ast/HasAccess.php
  src/Ast/HasPhpDoc.php
  src/Ast/PhpClass.php
  src/Ast/PhpClassMember.php
  src/Ast/PhpConstant.php
  src/Ast/PhpDoc.php
  src/Ast/PhpFile.php
  src/Ast/PhpMethod.php
  src/Ast/PhpProperty.php
  src/CodeGenerator.php
  src/Collections/EqualityHelper.php
  src/Collections/Map.php
  src/Collections/Set.php
  src/Collections/Vector.php
  src/Generation/EmptyClientGenerator.php
  src/Generation/GapicClientExamplesGenerator.php
  src/Generation/GapicClientGenerator.php
  src/Generation/MethodDetails.php
  src/Generation/ResourceDetails.php
  src/Generation/ResourcePatternDetails.php
  src/Generation/ResourcesGenerator.php
  src/Generation/ServiceDetails.php
  src/Generation/SourceFileContext.php
  src/Generation/TestNameValueProducer.php
  src/Generation/UnitTestsGenerator.php
  src/Main.php
  src/Utils/Formatter.php
  src/Utils/GapicYamlConfig.php
  src/Utils/ProtoAugmenter.php
  src/Utils/ProtoCatalog.php
  src/Utils/ProtoHelpers.php
  src/Utils/ResolvedType.php
  src/Utils/ServiceYamlConfig.php
  src/Utils/Type.php
Labels: cla: yes

#154 chore(engx): Add .php_cs.cache to .gitignore [ggphp]
  .gitignore
Labels: cla: yes

#155 [ggphp] fix(tests): Move SourceComparer into tests/Tools
  integration_tests/Main.php
  tests/Tools/SourceComparer.php
Labels: cla: yes

#156 [ggphp] fix(tests): Move run_protoc_plugin.sh into scripts/
  integration_tests/Invoker.php
  scripts/run_protoc_plugin.sh
Labels: cla: yes

#158 [ggphp] fix(build): Fix Bazel build, add gRPC dep to workspace
  WORKSPACE.bazel
Labels: api: cloudbuild, cla: yes

#159 [ggphp] fix(tests): Move integration_tests into tests/Integration
  .githooks/pre-commit
  composer.json
  tests/Integration/BUILD.bazel
  tests/Integration/Invoker.php
  tests/Integration/Main.php
  tests/Integration/goldens/asset/BUILD.bazel
  tests/Integration/goldens/asset/src/V1/AssetServiceClient.php
  tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/asset/src/V1/resources/asset_service_client_config.json
  tests/Integration/goldens/asset/src/V1/resources/asset_service_descriptor_config.php
  tests/Integration/goldens/asset/src/V1/resources/asset_service_rest_client_config.php
  tests/Integration/goldens/asset/tests/Unit/V1/AssetServiceClientTest.php
Labels: cla: yes

#161 [ggphp] fix(src): Move generated sources from src/ into generated/
  .githooks/pre-commit
  composer.json
  generated/GPBMetadata/Grpc/ServiceConfig/ServiceConfig.php
  generated/GPBMetadata/Plugin.php
  generated/Google/LongRunning/CancelOperationRequest.php
  generated/Google/LongRunning/DeleteOperationRequest.php
  generated/Google/LongRunning/GetOperationRequest.php
  generated/Google/LongRunning/ListOperationsRequest.php
  generated/Google/LongRunning/ListOperationsResponse.php
  generated/Google/LongRunning/Operation.php
  generated/Google/LongRunning/OperationInfo.php
  generated/Google/LongRunning/WaitOperationRequest.php
  generated/Google/Protobuf/Compiler/CodeGeneratorRequest.php
  generated/Google/Protobuf/Compiler/CodeGeneratorResponse.php
  generated/Google/Protobuf/Compiler/CodeGeneratorResponse/Feature.php
  generated/Google/Protobuf/Compiler/CodeGeneratorResponse/File.php
  generated/Google/Protobuf/Compiler/CodeGeneratorResponse_Feature.php
  generated/Google/Protobuf/Compiler/CodeGeneratorResponse_File.php
  generated/Google/Protobuf/Compiler/Version.php
  generated/Grpc/Service_config/CdsConfig.php
  generated/Grpc/Service_config/EdsLoadBalancingPolicyConfig.php
  generated/Grpc/Service_config/GrpcLbConfig.php
  generated/Grpc/Service_config/LoadBalancingConfig.php
  generated/Grpc/Service_config/LrsLoadBalancingPolicyConfig.php
  generated/Grpc/Service_config/LrsLoadBalancingPolicyConfig/Locality.php
  generated/Grpc/Service_config/LrsLoadBalancingPolicyConfig_Locality.php
  generated/Grpc/Service_config/MethodConfig.php
  generated/Grpc/Service_config/MethodConfig/HedgingPolicy.php
  generated/Grpc/Service_config/MethodConfig/Name.php
  generated/Grpc/Service_config/MethodConfig/RetryPolicy.php
  generated/Grpc/Service_config/MethodConfig_HedgingPolicy.php
  generated/Grpc/Service_config/MethodConfig_Name.php
  generated/Grpc/Service_config/MethodConfig_RetryPolicy.php
  generated/Grpc/Service_config/PickFirstConfig.php
  generated/Grpc/Service_config/PriorityLoadBalancingPolicyConfig.php
  generated/Grpc/Service_config/PriorityLoadBalancingPolicyConfig/Child.php
  generated/Grpc/Service_config/PriorityLoadBalancingPolicyConfig_Child.php
  generated/Grpc/Service_config/RoundRobinConfig.php
  generated/Grpc/Service_config/ServiceConfig.php
  generated/Grpc/Service_config/ServiceConfig/HealthCheckConfig.php
  generated/Grpc/Service_config/ServiceConfig/LoadBalancingPolicy.php
  generated/Grpc/Service_config/ServiceConfig/RetryThrottlingPolicy.php
  generated/Grpc/Service_config/ServiceConfig_HealthCheckConfig.php
  generated/Grpc/Service_config/ServiceConfig_LoadBalancingPolicy.php
  generated/Grpc/Service_config/ServiceConfig_RetryThrottlingPolicy.php
  generated/Grpc/Service_config/WeightedTargetLoadBalancingPolicyConfig.php
  generated/Grpc/Service_config/WeightedTargetLoadBalancingPolicyConfig/Target.php
  generated/Grpc/Service_config/WeightedTargetLoadBalancingPolicyConfig_Target.php
  generated/Grpc/Service_config/XdsConfig.php
  src/CodeGenerator.php
  src/Generation/ResourcesGenerator.php
  src/Generation/ServiceDetails.php
  src/Utils/Helpers.php
Labels: cla: yes

#163 [ggphp] chore(tests, engx): Add unit test for SourceComparer::compareJson
  tests/Tools/SourceComparer.php
  tests/Unit/Tools/SourceComparerTest.php
Labels: cla: yes

#164 [ggphp] chore(tests, engx): Add test for SourceComparer::compare
  tests/Tools/SourceComparer.php
  tests/Unit/Tools/SourceComparerTest.php
Labels: cla: yes

#165 [ggphp] feat(validation): Add PhpClassComparer and test - handles methods/functions
  tests/Tools/PhpClassComparer.php
  tests/Unit/Tools/PhpClassComparerTest.php
Labels: cla: yes

#169 [ggphp] feat(validation,tests) add namespace checking to PhpClassComparer
  tests/Tools/PhpClassComparer.php
  tests/Unit/Tools/PhpClassComparerTest.php
Labels: cla: yes

#170 [ggphp] feat(validation,tests): Add const handling to PhpClassComparer
  tests/Tools/PhpClassComparer.php
  tests/Unit/Tools/PhpClassComparerTest.php
Labels: cla: yes

#172 [ggphp] chore(engx): Remove Bazel rules debug printf
  rules_php_test/integration_test.bzl
Labels: cla: yes

#177 [ggphp] chore(engx): Lower-case invoked methods in ProtoTest
  tests/Unit/ProtoTests/ProtoTest.php
Labels: cla: yes

#174 [ggphp] fix(tests): Use semantic diffing in integration tests
  tests/Integration/Invoker.php
  tests/Integration/Main.php
Labels: cla: yes

#175 [ggphp] fix(tests): Check generated file list in unit tests
  tests/Unit/ProtoTests/ProtoTest.php
Labels: cla: yes

#176 [ggphp] fix(tests): suppress diff printing for PhpClassComparer tests
  tests/Unit/Tools/PhpClassComparerTest.php
Labels: cla: yes

#182 [ggphp] fix(tests): Refactor unit test protobuf and config loaders
  tests/Tools/ConfigLoader.php
  tests/Tools/GeneratorUtils.php
  tests/Tools/ProtoLoader.php
  tests/Unit/ProtoTests/ProtoTest.php
  tests/Unit/Utils/ProtoHelpersTest.php
Labels: cla: yes

#183 [ggphp] feat(tests): Add unit test updater scripts
  tests/Unit/ProtoTests/GoldenUpdateMain.php
  tests/Unit/ProtoTests/UnitGoldenUpdater.php
Labels: cla: yes

#184 [ggphp] chore(build): update compoesr.lock
  composer.lock
  psalm.xml
Labels: api: cloudbuild, cla: yes

#185 [ggphp] chore(engx): Remove unused imports, add rule to pre-commit linter
  .githooks/pre-commit
  src/Generation/FieldDetails.php
  src/Generation/GapicClientExamplesGenerator.php
  src/Generation/ResourceDetails.php
  src/Generation/ResourcePatternDetails.php
  src/Utils/GrpcServiceConfig.php
  src/Utils/ProtoAugmenter.php
  src/Utils/ProtoCatalog.php
  src/Utils/ProtoHelpers.php
  src/Utils/ServiceYamlConfig.php
  src/Utils/Type.php
Labels: cla: yes

#186 [ggphp] fix(bazel): update Bazel rules and docs with new tests/Integration dir
  DEVELOPMENT.md
  rules_php_test/integration_test.bzl
Labels: cla: yes

#187 [ggphp] chore(tests): add speech goldens, integration test def, and to CI and pre-commits
  .githooks/pre-commit
  .github/workflows/bazel_example.yml
  tests/Integration/BUILD.bazel
  tests/Integration/goldens/speech/BUILD.bazel
  tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php
  tests/Integration/goldens/speech/src/V1/SpeechClient.php
  tests/Integration/goldens/speech/src/V1/resources/speech_client_config.json
  tests/Integration/goldens/speech/src/V1/resources/speech_descriptor_config.php
  tests/Integration/goldens/speech/src/V1/resources/speech_rest_client_config.php
  tests/Integration/goldens/speech/tests/Unit/V1/SpeechClientTest.php
Labels: cla: yes

#196 [ggphp] fix(engx): fix batch-update in GoldenUpdateMain
  tests/Unit/ProtoTests/GoldenUpdateMain.php
Labels: cla: yes

#189 [ggphp] chore(tests): add videointelligence goldens and integraiton test def
  tests/Integration/BUILD.bazel
  tests/Integration/goldens/videointelligence/BUILD.bazel
  tests/Integration/goldens/videointelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  tests/Integration/goldens/videointelligence/src/V1/VideoIntelligenceServiceClient.php
  tests/Integration/goldens/videointelligence/src/V1/resources/video_intelligence_service_client_config.json
  tests/Integration/goldens/videointelligence/src/V1/resources/video_intelligence_service_descriptor_config.php
  tests/Integration/goldens/videointelligence/src/V1/resources/video_intelligence_service_rest_client_config.php
  tests/Integration/goldens/videointelligence/tests/Unit/V1/VideoIntelligenceServiceClientTest.php
Labels: cla: yes

#190 [ggphp] fix(validation,tests): forego comment diffs for methods in PhpClassComparer
  tests/Tools/PhpClassComparer.php
  tests/Unit/Tools/PhpClassComparerTest.php
Labels: cla: yes

#191 [ggphp] fix(gapic.yaml): Remove sample_code_init_fields, use default string values
  src/Generation/FieldDetails.php
  src/Generation/GapicClientExamplesGenerator.php
  tests/Integration/BUILD.bazel
  tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
  tests/Unit/ProtoTests/Basic/out/src/Gapic/BasicGapicClient.php
  tests/Unit/ProtoTests/BasicPaginated/out/src/Gapic/BasicPaginatedGapicClient.php
Labels: cla: yes, samples

#192 [ggphp] chore(engx): apply buildifier formatting to all BUILD files
  bazel_example/BUILD.bazel
  rules_php_gapic/BUILD.bazel
Labels: cla: yes

#197 [ggphp] fix(bazel): tarball only used dirs into php_microgen_binary
  rules_php_gapic/php.bzl
Labels: cla: yes

#198 [ggphp] fix(lint): Add full PSR2 linting rules, fix linter comment un-indentation
  src/Generation/UnitTestsGenerator.php
  src/Utils/Formatter.php
  tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/asset/tests/Unit/V1/AssetServiceClientTest.php
  tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
  tests/Integration/goldens/redis/tests/Unit/V1/CloudRedisClientTest.php
  tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php
  tests/Integration/goldens/speech/tests/Unit/V1/SpeechClientTest.php
  tests/Integration/goldens/videointelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  tests/Integration/goldens/videointelligence/tests/Unit/V1/VideoIntelligenceServiceClientTest.php
  tests/Unit/ProtoTests/Basic/out/tests/Unit/BasicClientTest.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/src/Gapic/BasicBidiStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/tests/Unit/BasicBidiStreamingClientTest.php
  tests/Unit/ProtoTests/BasicClientStreaming/out/tests/Unit/BasicClientStreamingClientTest.php
  tests/Unit/ProtoTests/BasicLro/out/src/Gapic/BasicLroGapicClient.php
  tests/Unit/ProtoTests/BasicLro/out/tests/Unit/BasicLroClientTest.php
  tests/Unit/ProtoTests/BasicPaginated/out/src/Gapic/BasicPaginatedGapicClient.php
  tests/Unit/ProtoTests/BasicPaginated/out/tests/Unit/BasicPaginatedClientTest.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/tests/Unit/BasicServerStreamingClientTest.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/GrpcServiceConfigWithRetry1Client.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/resources/grpc_service_config_with_retry1_descriptor_config.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/tests/Unit/GrpcServiceConfigWithRetry1ClientTest.php
Labels: cla: yes

#199 [ggphp] fix(mono): Decouple timeouts from service.yaml, bypass timeout_millis in mono_tests
  .github/workflows/bazel_example.yml
  src/Generation/ResourcesGenerator.php
  tests/Integration/Main.php
  tests/Tools/SourceComparer.php
Labels: cla: yes

#200 [ggphp] fix(mono): Remove sample_code_init_fields usage from test codegen
  src/CodeGenerator.php
  src/Generation/GapicClientExamplesGenerator.php
  src/Generation/TestNameValueProducer.php
  src/Generation/UnitTestsGenerator.php
  tests/Integration/Main.php
Labels: cla: yes, samples

#201 [ggphp] fix(mono): Sort methods alphabetically, not by gapic.yaml
  src/Generation/ServiceDetails.php
  tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/asset/src/V1/resources/asset_service_client_config.json
  tests/Integration/goldens/asset/src/V1/resources/asset_service_descriptor_config.php
  tests/Integration/goldens/asset/src/V1/resources/asset_service_rest_client_config.php
  tests/Integration/goldens/asset/tests/Unit/V1/AssetServiceClientTest.php
  tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
  tests/Integration/goldens/redis/src/V1/resources/cloud_redis_client_config.json
  tests/Integration/goldens/redis/src/V1/resources/cloud_redis_descriptor_config.php
  tests/Integration/goldens/redis/src/V1/resources/cloud_redis_rest_client_config.php
  tests/Integration/goldens/redis/tests/Unit/V1/CloudRedisClientTest.php
  tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php
  tests/Integration/goldens/speech/src/V1/resources/speech_client_config.json
  tests/Integration/goldens/speech/src/V1/resources/speech_rest_client_config.php
  tests/Integration/goldens/speech/tests/Unit/V1/SpeechClientTest.php
  tests/Integration/goldens/videointelligence/tests/Unit/V1/VideoIntelligenceServiceClientTest.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/src/Gapic/BasicServerStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/src/resources/basic_server_streaming_client_config.json
  tests/Unit/ProtoTests/BasicServerStreaming/out/src/resources/basic_server_streaming_descriptor_config.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/tests/Unit/BasicServerStreamingClientTest.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/resources/grpc_service_config_with_retry1_client_config.json
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/resources/grpc_service_config_with_retry1_descriptor_config.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/tests/Unit/GrpcServiceConfigWithRetry1ClientTest.php
Labels: cla: yes

#202 [ggphp] fix(bazel): Add gapic-generator to plugin deps
  rules_php_gapic/php.bzl
Labels: cla: yes

#204 [ggphp] fix(mono): remove unused gapic.yaml from codegen classes
  src/CodeGenerator.php
  src/Generation/GapicClientExamplesGenerator.php
  src/Generation/GapicClientGenerator.php
  src/Generation/ServiceDetails.php
Labels: cla: yes

#205 [ggphp] chore(validation,tests): refactor JsonComparer out of SourceComparer
  tests/Integration/Main.php
  tests/Tools/JsonComparer.php
  tests/Tools/SourceComparer.php
  tests/Unit/Tools/JsonComparerTest.php
  tests/Unit/Tools/SourceComparerTest.php
Labels: cla: yes

#206 [ggphp] fix(mono): Decouple retries from gapic.yaml, don't generate unused configs
  src/CodeGenerator.php
  src/Generation/ResourcesGenerator.php
  tests/Tools/JsonComparer.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/resources/grpc_service_config_with_retry1_client_config.json
Labels: cla: yes

#207 [ggphp] fix(mono): Decouple retry config from service.yaml
  src/CodeGenerator.php
  src/Generation/ResourcesGenerator.php
Labels: cla: yes

#208 [ggphp] fix(mono): Use current year in license headers
  src/CodeGenerator.php
  src/Main.php
  tests/Integration/goldens/asset/src/V1/AssetServiceClient.php
  tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/asset/tests/Unit/V1/AssetServiceClientTest.php
  tests/Integration/goldens/redis/src/V1/CloudRedisClient.php
  tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
  tests/Integration/goldens/redis/tests/Unit/V1/CloudRedisClientTest.php
  tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php
  tests/Integration/goldens/speech/src/V1/SpeechClient.php
  tests/Integration/goldens/speech/tests/Unit/V1/SpeechClientTest.php
  tests/Integration/goldens/videointelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  tests/Integration/goldens/videointelligence/src/V1/VideoIntelligenceServiceClient.php
  tests/Integration/goldens/videointelligence/tests/Unit/V1/VideoIntelligenceServiceClientTest.php
  tests/Tools/GeneratorUtils.php
Labels: cla: yes

#209 [ggphp] fix(mono): Remove unused imports in generated files
  generated/GPBMetadata/Gapic/Metadata/GapicMetadata.php
  generated/Google/Gapic/Metadata/GapicMetadata.php
  generated/Google/Gapic/Metadata/GapicMetadata/MethodList.php
  generated/Google/Gapic/Metadata/GapicMetadata/ServiceAsClient.php
  generated/Google/Gapic/Metadata/GapicMetadata/ServiceForTransport.php
  generated/Google/Gapic/Metadata/GapicMetadata_MethodList.php
  generated/Google/Gapic/Metadata/GapicMetadata_ServiceAsClient.php
  generated/Google/Gapic/Metadata/GapicMetadata_ServiceForTransport.php
  src/Utils/Formatter.php
  tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/asset/tests/Unit/V1/AssetServiceClientTest.php
  tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
  tests/Integration/goldens/redis/tests/Unit/V1/CloudRedisClientTest.php
  tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php
  tests/Integration/goldens/speech/tests/Unit/V1/SpeechClientTest.php
  tests/Integration/goldens/videointelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  tests/Integration/goldens/videointelligence/tests/Unit/V1/VideoIntelligenceServiceClientTest.php
  tests/Unit/ProtoTests/Basic/out/src/Gapic/BasicGapicClient.php
  tests/Unit/ProtoTests/Basic/out/tests/Unit/BasicClientTest.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/src/Gapic/BasicBidiStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/tests/Unit/BasicBidiStreamingClientTest.php
  tests/Unit/ProtoTests/BasicClientStreaming/out/src/Gapic/BasicClientStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicClientStreaming/out/tests/Unit/BasicClientStreamingClientTest.php
  tests/Unit/ProtoTests/BasicLro/out/src/Gapic/BasicLroGapicClient.php
  tests/Unit/ProtoTests/BasicLro/out/tests/Unit/BasicLroClientTest.php
  tests/Unit/ProtoTests/BasicPaginated/out/src/Gapic/BasicPaginatedGapicClient.php
  tests/Unit/ProtoTests/BasicPaginated/out/tests/Unit/BasicPaginatedClientTest.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/src/Gapic/BasicServerStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/tests/Unit/BasicServerStreamingClientTest.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/tests/Unit/GrpcServiceConfigWithRetry1ClientTest.php
Labels: cla: yes

#210 [ggphp] feat(metadata): Add gapic_metadata.json generation, CLI flag
  rules_php_gapic/php_gapic.bzl
  src/CodeGenerator.php
  src/Generation/GapicMetadataGenerator.php
  src/Main.php
  tests/Integration/goldens/asset/src/V1/gapic_metadata.json
  tests/Integration/goldens/redis/src/V1/gapic_metadata.json
  tests/Integration/goldens/speech/src/V1/gapic_metadata.json
  tests/Integration/goldens/videointelligence/src/V1/gapic_metadata.json
  tests/Tools/GeneratorUtils.php
Labels: cla: yes

#211 [ggphp] chore(mixins): Initial KMS goldens with naive mixins
  tests/Integration/goldens/kms/BUILD.bazel
  tests/Integration/goldens/kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  tests/Integration/goldens/kms/src/V1/KeyManagementServiceClient.php
  tests/Integration/goldens/kms/src/V1/gapic_metadata.json
  tests/Integration/goldens/kms/src/V1/resources/key_management_service_client_config.json
  tests/Integration/goldens/kms/src/V1/resources/key_management_service_descriptor_config.php
  tests/Integration/goldens/kms/src/V1/resources/key_management_service_rest_client_config.php
  tests/Integration/goldens/kms/tests/Unit/V1/KeyManagementServiceClientTest.php
Labels: cla: yes

#212 [ggphp] feat(mixins): Add mixins to the PHP microgenerator
  src/CodeGenerator.php
  src/Generation/GapicClientGenerator.php
  src/Generation/GapicMetadataGenerator.php
  src/Generation/MethodDetails.php
  src/Generation/ResourcesGenerator.php
  src/Generation/ServiceDetails.php
  src/Generation/UnitTestsGenerator.php
  src/Utils/ServiceYamlConfig.php
  tests/Integration/BUILD.bazel
  tests/Integration/apis/kms/v1/cloudkms_grpc_service_config.json
  tests/Integration/apis/kms/v1/cloudkms_test_mixins_v1.yaml
  tests/Integration/apis/kms/v1/resources.proto
  tests/Integration/apis/kms/v1/service.proto
  tests/Integration/goldens/kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  tests/Integration/goldens/kms/src/V1/gapic_metadata.json
  tests/Integration/goldens/kms/src/V1/resources/key_management_service_client_config.json
  tests/Integration/goldens/kms/src/V1/resources/key_management_service_rest_client_config.php
  tests/Integration/goldens/kms/tests/Unit/V1/KeyManagementServiceClientTest.php
  tests/Unit/ProtoTests/Basic/out/src/gapic_metadata.json
  tests/Unit/ProtoTests/BasicBidiStreaming/out/src/gapic_metadata.json
  tests/Unit/ProtoTests/BasicClientStreaming/out/src/gapic_metadata.json
  tests/Unit/ProtoTests/BasicLro/out/src/gapic_metadata.json
  tests/Unit/ProtoTests/BasicPaginated/out/src/gapic_metadata.json
  tests/Unit/ProtoTests/BasicServerStreaming/out/src/gapic_metadata.json
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/gapic_metadata.json
Labels: cla: yes

#216 [ggphp] fix(mixins): enable generation of standalone mixin-listed APIs, add tests
  src/CodeGenerator.php
  tests/Integration/BUILD.bazel
  tests/Integration/apis/iam/v1/iam_api.yaml
  tests/Integration/apis/iam/v1/iam_gapic.yaml
  tests/Integration/goldens/iam/BUILD.bazel
  tests/Integration/goldens/iam/src/V1/Gapic/IAMPolicyGapicClient.php
  tests/Integration/goldens/iam/src/V1/IAMPolicyClient.php
  tests/Integration/goldens/iam/src/V1/gapic_metadata.json
  tests/Integration/goldens/iam/src/V1/resources/iam_policy_client_config.json
  tests/Integration/goldens/iam/src/V1/resources/iam_policy_descriptor_config.php
  tests/Integration/goldens/iam/src/V1/resources/iam_policy_rest_client_config.php
  tests/Integration/goldens/iam/tests/Unit/V1/IAMPolicyClientTest.php
Labels: cla: yes

#213 [ggphp] fix(tests): Run integ tests against microgen w/o gapic.yaml, service.yaml
  tests/Integration/Invoker.php
  tests/Integration/Main.php
Labels: cla: yes

#214 [ggphp] fix(mono): Remove @experimental tags from generated client
  src/Generation/GapicClientGenerator.php
  tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
  tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php
  tests/Integration/goldens/videointelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  tests/Unit/ProtoTests/Basic/out/src/Gapic/BasicGapicClient.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/src/Gapic/BasicBidiStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicClientStreaming/out/src/Gapic/BasicClientStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicLro/out/src/Gapic/BasicLroGapicClient.php
  tests/Unit/ProtoTests/BasicPaginated/out/src/Gapic/BasicPaginatedGapicClient.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/src/Gapic/BasicServerStreamingGapicClient.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php
Labels: cla: yes

#215 [ggphp] feat(validation): Add gapic client lib differ script
  validation/GapicDifferMain.php
Labels: cla: yes

#218 [ggphp] feat(validation): swap (self::nameTemplate == null) tokens in microgen validation
  validation/GapicDifferMain.php
Labels: cla: yes

#219 fix(validation): Sort configs before comparison
  validation/GapicDifferMain.php
Labels: cla: yes

#220 [ggphp] fix(resnames): handle singletons in pathTemplateMap
  src/Generation/ResourceDetails.php
  src/Generation/ResourcePatternDetails.php
  src/Generation/ServiceDetails.php
  tests/Integration/BUILD.bazel
  tests/Integration/Main.php
  tests/Integration/goldens/logging/BUILD.bazel
  tests/Integration/goldens/logging/src/V2/ConfigServiceV2Client.php
  tests/Integration/goldens/logging/src/V2/Gapic/ConfigServiceV2GapicClient.php
  tests/Integration/goldens/logging/src/V2/Gapic/LoggingServiceV2GapicClient.php
  tests/Integration/goldens/logging/src/V2/Gapic/MetricsServiceV2GapicClient.php
  tests/Integration/goldens/logging/src/V2/LoggingServiceV2Client.php
  tests/Integration/goldens/logging/src/V2/MetricsServiceV2Client.php
  tests/Integration/goldens/logging/src/V2/gapic_metadata.json
  tests/Integration/goldens/logging/src/V2/resources/config_service_v2_client_config.json
  tests/Integration/goldens/logging/src/V2/resources/config_service_v2_descriptor_config.php
  tests/Integration/goldens/logging/src/V2/resources/config_service_v2_rest_client_config.php
  tests/Integration/goldens/logging/src/V2/resources/logging_service_v2_client_config.json
  tests/Integration/goldens/logging/src/V2/resources/logging_service_v2_descriptor_config.php
  tests/Integration/goldens/logging/src/V2/resources/logging_service_v2_rest_client_config.php
  tests/Integration/goldens/logging/src/V2/resources/metrics_service_v2_client_config.json
  tests/Integration/goldens/logging/src/V2/resources/metrics_service_v2_descriptor_config.php
  tests/Integration/goldens/logging/src/V2/resources/metrics_service_v2_rest_client_config.php
  tests/Integration/goldens/logging/tests/Unit/V2/ConfigServiceV2ClientTest.php
  tests/Integration/goldens/logging/tests/Unit/V2/LoggingServiceV2ClientTest.php
  tests/Integration/goldens/logging/tests/Unit/V2/MetricsServiceV2ClientTest.php
Labels: cla: yes

#221 [ggphp] feat(resources): handle batching in gapic.yaml
  src/CodeGenerator.php
  src/Generation/ResourcesGenerator.php
  tests/Integration/goldens/logging/src/V2/resources/logging_service_v2_client_config.json
Labels: cla: yes

#222 [ggphp] chore(build): Enable release-please
  .github/release-please.yml
Labels: cla: yes

#223 [ggp] fix(codegen, lint): use multi-line docblocks in generated srcs
  src/Utils/Formatter.php
  tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/asset/tests/Unit/V1/AssetServiceClientTest.php
  tests/Integration/goldens/kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  tests/Integration/goldens/kms/tests/Unit/V1/KeyManagementServiceClientTest.php
  tests/Integration/goldens/logging/src/V2/Gapic/ConfigServiceV2GapicClient.php
  tests/Integration/goldens/logging/src/V2/Gapic/LoggingServiceV2GapicClient.php
  tests/Integration/goldens/logging/src/V2/Gapic/MetricsServiceV2GapicClient.php
  tests/Integration/goldens/logging/tests/Unit/V2/ConfigServiceV2ClientTest.php
  tests/Integration/goldens/logging/tests/Unit/V2/LoggingServiceV2ClientTest.php
  tests/Integration/goldens/logging/tests/Unit/V2/MetricsServiceV2ClientTest.php
  tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
  tests/Integration/goldens/redis/tests/Unit/V1/CloudRedisClientTest.php
  tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php
  tests/Integration/goldens/speech/tests/Unit/V1/SpeechClientTest.php
  tests/Integration/goldens/videointelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  tests/Integration/goldens/videointelligence/tests/Unit/V1/VideoIntelligenceServiceClientTest.php
  tests/Unit/ProtoTests/Basic/out/src/Gapic/BasicGapicClient.php
  tests/Unit/ProtoTests/Basic/out/tests/Unit/BasicClientTest.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/src/Gapic/BasicBidiStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicBidiStreaming/out/tests/Unit/BasicBidiStreamingClientTest.php
  tests/Unit/ProtoTests/BasicClientStreaming/out/src/Gapic/BasicClientStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicClientStreaming/out/tests/Unit/BasicClientStreamingClientTest.php
  tests/Unit/ProtoTests/BasicLro/out/src/Gapic/BasicLroGapicClient.php
  tests/Unit/ProtoTests/BasicLro/out/tests/Unit/BasicLroClientTest.php
  tests/Unit/ProtoTests/BasicPaginated/out/src/Gapic/BasicPaginatedGapicClient.php
  tests/Unit/ProtoTests/BasicPaginated/out/tests/Unit/BasicPaginatedClientTest.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/src/Gapic/BasicServerStreamingGapicClient.php
  tests/Unit/ProtoTests/BasicServerStreaming/out/tests/Unit/BasicServerStreamingClientTest.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php
  tests/Unit/ProtoTests/GrpcServiceConfig/out/tests/Unit/GrpcServiceConfigWithRetry1ClientTest.php
Labels: cla: yes

#225 [ggp] fix(client): Generate requestParams descriptor for RPCs with 2+ routing headers
  tests/Integration/goldens/container/BUILD.bazel
  tests/Integration/goldens/container/src/V1/ClusterManagerClient.php
  tests/Integration/goldens/container/src/V1/Gapic/ClusterManagerGapicClient.php
  tests/Integration/goldens/container/src/V1/gapic_metadata.json
  tests/Integration/goldens/container/src/V1/resources/cluster_manager_client_config.json
  tests/Integration/goldens/container/src/V1/resources/cluster_manager_descriptor_config.php
  tests/Integration/goldens/container/src/V1/resources/cluster_manager_rest_client_config.php
  tests/Integration/goldens/container/tests/Unit/V1/ClusterManagerClientTest.php
Labels: cla: yes

#226 [ggp] fix(client): handle >1 routing headers
  src/Generation/GapicClientGenerator.php
  src/Generation/MethodDetails.php
  tests/Integration/BUILD.bazel
Labels: cla: yes

#227 [ggp] chore(tests): Update IAM goldens
  tests/Integration/goldens/iam/src/V1/Gapic/IAMPolicyGapicClient.php
  tests/Integration/goldens/iam/tests/Unit/V1/IAMPolicyClientTest.php
Labels: cla: yes

#228 [ggp] fix(engx, lint): relint all files
  src/Generation/ResourcesGenerator.php
  tests/Integration/Main.php
  tests/Tools/ConfigLoader.php
  tests/Tools/GeneratorUtils.php
  tests/Tools/JsonComparer.php
  tests/Tools/PhpClassComparer.php
  tests/Tools/PhpComparerMain.php
  tests/Tools/PhpConfigComparer.php
  tests/Tools/ProtoLoader.php
  tests/Unit/Ast/ASTTest.php
  tests/Unit/Ast/PhpDocTest.php
  tests/Unit/Collections/MapTest.php
  tests/Unit/Collections/SetTest.php
  tests/Unit/Collections/VectorTest.php
  tests/Unit/ProtoTests/GoldenUpdateMain.php
  tests/Unit/ProtoTests/ProtoTest.php
  tests/Unit/ProtoTests/UnitGoldenUpdater.php
  tests/Unit/Tools/SourceComparerTest.php
  tests/Unit/Utils/TypeTest.php
  tests/Unit/autoload.php
Labels: cla: yes

#229 [ggp] build(engx): Run lint checks on all src and test dirs in pre-commit
  .githooks/pre-commit
Labels: cla: yes

#230 [ggp] build(engx): Add all Bazel integration tests to CI and pre-commit
  .githooks/pre-commit
  .github/workflows/bazel_example.yml
Labels: cla: yes

#231 [ggp] fix(tests): Add initial dataproc goldens
  tests/Integration/goldens/dataproc/BUILD.bazel
  tests/Integration/goldens/dataproc/src/V1/AutoscalingPolicyServiceClient.php
  tests/Integration/goldens/dataproc/src/V1/ClusterControllerClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/AutoscalingPolicyServiceGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/JobControllerGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/WorkflowTemplateServiceGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/JobControllerClient.php
  tests/Integration/goldens/dataproc/src/V1/WorkflowTemplateServiceClient.php
  tests/Integration/goldens/dataproc/src/V1/gapic_metadata.json
  tests/Integration/goldens/dataproc/src/V1/resources/autoscaling_policy_service_client_config.json
  tests/Integration/goldens/dataproc/src/V1/resources/autoscaling_policy_service_descriptor_config.php
  tests/Integration/goldens/dataproc/src/V1/resources/autoscaling_policy_service_rest_client_config.php
  tests/Integration/goldens/dataproc/src/V1/resources/cluster_controller_client_config.json
  tests/Integration/goldens/dataproc/src/V1/resources/cluster_controller_descriptor_config.php
  tests/Integration/goldens/dataproc/src/V1/resources/cluster_controller_rest_client_config.php
  tests/Integration/goldens/dataproc/src/V1/resources/job_controller_client_config.json
  tests/Integration/goldens/dataproc/src/V1/resources/job_controller_descriptor_config.php
  tests/Integration/goldens/dataproc/src/V1/resources/job_controller_rest_client_config.php
  tests/Integration/goldens/dataproc/src/V1/resources/workflow_template_service_client_config.json
  tests/Integration/goldens/dataproc/src/V1/resources/workflow_template_service_descriptor_config.php
  tests/Integration/goldens/dataproc/src/V1/resources/workflow_template_service_rest_client_config.php
  tests/Integration/goldens/dataproc/tests/Unit/V1/AutoscalingPolicyServiceClientTest.php
  tests/Integration/goldens/dataproc/tests/Unit/V1/ClusterControllerClientTest.php
  tests/Integration/goldens/dataproc/tests/Unit/V1/JobControllerClientTest.php
  tests/Integration/goldens/dataproc/tests/Unit/V1/WorkflowTemplateServiceClientTest.php
Labels: cla: yes

#232 [ggp] fix(tests): Add initial functions goldens
  tests/Integration/goldens/functions/BUILD.bazel
  tests/Integration/goldens/functions/src/V1/CloudFunctionsServiceClient.php
  tests/Integration/goldens/functions/src/V1/Gapic/CloudFunctionsServiceGapicClient.php
  tests/Integration/goldens/functions/src/V1/gapic_metadata.json
  tests/Integration/goldens/functions/src/V1/resources/cloud_functions_service_client_config.json
  tests/Integration/goldens/functions/src/V1/resources/cloud_functions_service_descriptor_config.php
  tests/Integration/goldens/functions/src/V1/resources/cloud_functions_service_rest_client_config.php
  tests/Integration/goldens/functions/tests/Unit/V1/CloudFunctionsServiceClientTest.php
Labels: cla: yes

#233 [ggp] fix(client): set request parameters for only required fields (phase 1/2)
  composer.json
  composer.lock
  src/Generation/GapicClientGenerator.php
  tests/Integration/BUILD.bazel
  tests/Integration/Main.php
  tests/Integration/goldens/container/src/V1/Gapic/ClusterManagerGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/JobControllerGapicClient.php
  tests/Integration/goldens/kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  tests/Unit/ProtoTests/GoldenUpdateMain.php
  tests/Unit/ProtoTests/ProtoTest.php
  tests/Unit/ProtoTests/RoutingHeaders/out/src/Gapic/RoutingHeadersGapicClient.php
  tests/Unit/ProtoTests/RoutingHeaders/out/src/RoutingHeadersClient.php
  tests/Unit/ProtoTests/RoutingHeaders/out/src/gapic_metadata.json
  tests/Unit/ProtoTests/RoutingHeaders/out/src/resources/routing_headers_client_config.json
  tests/Unit/ProtoTests/RoutingHeaders/out/src/resources/routing_headers_descriptor_config.php
  tests/Unit/ProtoTests/RoutingHeaders/out/src/resources/routing_headers_rest_client_config.php
  tests/Unit/ProtoTests/RoutingHeaders/out/tests/Unit/RoutingHeadersClientTest.php
  tests/Unit/ProtoTests/RoutingHeaders/routing-headers.proto
Labels: cla: yes

#234 [ggp] fix(client): Handle optional and required request params (phase 2/2)
  src/Generation/GapicClientGenerator.php
  tests/Integration/Main.php
  tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
  tests/Integration/goldens/container/src/V1/Gapic/ClusterManagerGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/AutoscalingPolicyServiceGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/JobControllerGapicClient.php
  tests/Integration/goldens/dataproc/src/V1/Gapic/WorkflowTemplateServiceGapicClient.php
  tests/Integration/goldens/functions/src/V1/Gapic/CloudFunctionsServiceGapicClient.php
  tests/Integration/goldens/iam/src/V1/Gapic/IAMPolicyGapicClient.php
  tests/Integration/goldens/kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  tests/Integration/goldens/logging/src/V2/Gapic/ConfigServiceV2GapicClient.php
  tests/Integration/goldens/logging/src/V2/Gapic/LoggingServiceV2GapicClient.php
  tests/Integration/goldens/logging/src/V2/Gapic/MetricsServiceV2GapicClient.php
  tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
  tests/Unit/ProtoTests/RoutingHeaders/out/src/Gapic/RoutingHeadersGapicClient.php
Labels: cla: yes
